version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Reactivities.API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - frontend

  frontend:
    build:
      context: ./client-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
